### ISSUE TITLE
Error during the start

### ISSUE THREAD

**Issue by Gaploid** [Azure/BatchLabs#261]
Hi,
Any ideas why it did not started? I`ve tried to start it "npm run electron"

Here is the log:
```
gaploid@BatchLabsUbuntu:~/BatchLabs$ cat npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'electron' ]
2 info using npm@4.1.2
3 info using node@v7.7.3
4 verbose run-script [ 'preelectron', 'electron', 'postelectron' ]
5 info lifecycle batch-labs@0.0.1~preelectron: batch-labs@0.0.1
6 silly lifecycle batch-labs@0.0.1~preelectron: no script for preelectron, continuing
7 info lifecycle batch-labs@0.0.1~electron: batch-labs@0.0.1
8 verbose lifecycle batch-labs@0.0.1~electron: unsafe-perm in lifecycle true
9 verbose lifecycle batch-labs@0.0.1~electron: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/gaploid/BatchLabs/node_modules/.bin:/home/gaploid/bin:/home/gaploid/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle batch-labs@0.0.1~electron: CWD: /home/gaploid/BatchLabs
11 silly lifecycle batch-labs@0.0.1~electron: Args: [ '-c', 'electron build/client/main.js' ]
12 silly lifecycle batch-labs@0.0.1~electron: Returned: code: 1  signal: null
13 info lifecycle batch-labs@0.0.1~electron: Failed to exec electron script
14 verbose stack Error: batch-labs@0.0.1 electron: `electron build/client/main.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid batch-labs@0.0.1
16 verbose cwd /home/gaploid/BatchLabs
17 error Linux 4.4.0-66-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "electron"
19 error node v7.7.3
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error batch-labs@0.0.1 electron: `electron build/client/main.js`
22 error Exit status 1
23 error Failed at the batch-labs@0.0.1 electron script 'electron build/client/main.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the batch-labs package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     electron build/client/main.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs batch-labs
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls batch-labs
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by timotheeguerin** [comment]
Did you had to upgrade node or was it at `7.7.3` from the start?
If so can you try deleting the `node_modules` folder and running `npm install` again
